name: effect-env
dependencies:
    - python=2.6
    - psycopg2
    - pip:
        - digEntityMerger
        - digSparkUtil
        - xmljson
        - requests
        - digExtractor
        - digEmailExtractor
        - jsonpath-rw
        - jsonpath-rw-ext